version: '3'
services:
  badhan-test-service:
    container_name: badhan-test-container
    build:
      context: .
    volumes:
      - '.:/badhan-test'
      - './node_modules:/badhan-test/node_modules'
    network_mode: host
    extra_hosts:
      - "host.docker.internal:host-gateway"